version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: file-watcher
      POSTGRES_PASSWORD: file-watcher

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: file-watcher
      POSTGRES_USER: file-watcher
      POSTGRES_PASSWORD: file-watcher